"use strict";

const ACTION_STATES = {
  WAITING_ON_YOUR_REPLY: "waiting_on_your_reply",
  NEEDS_APPROVAL: "needs_approval",
  NEEDS_FOLLOW_UP: "needs_follow_up",
  WAITING_ON_OTHERS: "waiting_on_others",
  NO_ACTION_NEEDED: "no_action_needed",
};

const ACTION_STATE_META = {
  [ACTION_STATES.WAITING_ON_YOUR_REPLY]: {
    label: "Waiting on your reply",
    priorityWeight: 34,
  },
  [ACTION_STATES.NEEDS_APPROVAL]: {
    label: "Needs approval",
    priorityWeight: 40,
  },
  [ACTION_STATES.NEEDS_FOLLOW_UP]: {
    label: "Needs follow-up",
    priorityWeight: 24,
  },
  [ACTION_STATES.WAITING_ON_OTHERS]: {
    label: "Waiting on others",
    priorityWeight: 8,
  },
  [ACTION_STATES.NO_ACTION_NEEDED]: {
    label: "No action needed",
    priorityWeight: 0,
  },
};

const SOURCE_THRESHOLDS = {
  default: {
    replyWindowHours: 24,
    approvalWindowHours: 72,
    followUpWindowHours: 120,
    promiseFollowUpHours: 36,
    waitingOnOthersWindowHours: 120,
    maxConversations: 12,
    messageLimit: 18,
  },
  gmail: {
    replyWindowHours: 24,
    approvalWindowHours: 96,
    followUpWindowHours: 168,
    promiseFollowUpHours: 48,
    waitingOnOthersWindowHours: 168,
    maxConversations: 16,
    messageLimit: 8,
    lookbackDays: 14,
  },
  slack: {
    replyWindowHours: 24,
    approvalWindowHours: 72,
    followUpWindowHours: 96,
    promiseFollowUpHours: 36,
    waitingOnOthersWindowHours: 96,
    maxConversations: 14,
    messageLimit: 24,
  },
  telegram: {
    replyWindowHours: 24,
    approvalWindowHours: 72,
    followUpWindowHours: 120,
    promiseFollowUpHours: 36,
    waitingOnOthersWindowHours: 120,
    maxConversations: 12,
    messageLimit: 24,
  },
  whatsapp: {
    replyWindowHours: 24,
    approvalWindowHours: 72,
    followUpWindowHours: 120,
    promiseFollowUpHours: 36,
    waitingOnOthersWindowHours: 120,
    maxConversations: 10,
    messageLimit: 20,
  },
};

const INTENT_PATTERNS = {
  approval: [
    /\bapprove\b/,
    /\bapproval\b/,
    /\bsign[\s-]?off\b/,
    /\bgreen[\s-]?light\b/,
    /\bcan i proceed\b/,
    /\bfinal confirmation\b/,
    /\bneed your approval\b/,
    /\bkindly approve\b/,
    /\bplease approve\b/,
    /\bpermission to\b/,
  ],
  request: [
    /\bcan you\b/,
    /\bcould you\b/,
    /\bwould you\b/,
    /\bwill you\b/,
    /\bplease send\b/,
    /\bplease share\b/,
    /\bplease review\b/,
    /\bplease check\b/,
    /\bplease confirm\b/,
    /\bneed your input\b/,
    /\bneed your response\b/,
    /\blet me know\b/,
    /\bplease update\b/,
    /\bany update\b/,
    /\bwhat's the eta\b/,
    /\bwhat is the eta\b/,
    /\bwhen can you\b/,
    /\bcan i\b/,
    /\bshould we\b/,
  ],
  followUp: [
    /\bfollow[\s-]?up\b/,
    /\bfollowing up\b/,
    /\bcircling back\b/,
    /\bchecking in\b/,
    /\bjust checking\b/,
    /\bwaiting for your response\b/,
    /\bwaiting for your update\b/,
    /\breminder\b/,
    /\bpinging you\b/,
  ],
  promise: [
    /\bi(?:'| wi)ll\b/,
    /\blet me\b/,
    /\bi can send\b/,
    /\bi can share\b/,
    /\bi can confirm\b/,
    /\bi'll send\b/,
    /\bi'll share\b/,
    /\bi'll get back\b/,
    /\bi'll follow up\b/,
    /\bi will send\b/,
    /\bi will share\b/,
    /\bi will confirm\b/,
    /\bi will get back\b/,
  ],
  resolution: [
    /\bthanks[,!.\s]*that(?:'s| is) all\b/,
    /\bresolved\b/,
    /\bclosed\b/,
    /\bwe're good\b/,
    /\blooks good\b/,
    /\bapproved\b/,
    /\bdone\b/,
    /\bhandled\b/,
    /\ball set\b/,
    /\bthank you\b/,
    /\bsgtm\b/,
  ],
  informational: [
    /\bfyi\b/,
    /\bfor your information\b/,
    /\bsharing for visibility\b/,
    /\bno action needed\b/,
    /\bheads up\b/,
    /\bjust so you know\b/,
  ],
  invitation: [
    /\binvitation:\b/,
    /\bupdated invitation:\b/,
    /\bcalendar invite\b/,
    /\bmeeting invitation\b/,
    /\bgoogle calendar\b/,
    /\bgoogle meet\b/,
    /\baccepted:\b/,
    /\bdeclined:\b/,
    /\btentative:\b/,
  ],
  newsletter: [
    /\bnewsletter\b/,
    /\bdigest\b/,
    /\bweekly summary\b/,
    /\bdaily summary\b/,
    /\bunsubscribe\b/,
    /\bpromo\b/,
    /\bdiscount\b/,
    /\boffer ends\b/,
    /\bmarketing\b/,
  ],
  automatedSender: [
    /\bno-?reply\b/,
    /\bdo-?not-?reply\b/,
    /\bdonotreply\b/,
    /\bmailer-daemon\b/,
    /\bauto-?reply\b/,
    /\bbounce\b/,
    /\bnotification\b/,
    /\balert\b/,
    /\bslackbot\b/,
    /\bbot\b/,
  ],
  directAddressPrefixes: [
    /^\s*hi\b/,
    /^\s*hello\b/,
    /^\s*hey\b/,
    /^\s*dear\b/,
  ],
};

module.exports = {
  ACTION_STATES,
  ACTION_STATE_META,
  SOURCE_THRESHOLDS,
  INTENT_PATTERNS,
};
